name: Nightly TypeScript Run

# run the typescript@next Ember Try job...
jobs:
  ts-next:
    name: typescript@next
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: pnpm install
      - run: pnpm add --save-dev typescript@next
      - run: pnpm type-check

# ...nightly at midnight
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
